Idomeneo, re di Creta, K. 366: Overture
Idomeneo, re di Creta, K. 366: 1. Recitativo 'Quando avran fine omai'
Idomeneo, re di Creta, K. 366: 2. Aria 'Padre, germani, addio!'
Idomeneo, re di Creta, K. 366: 3. Recitativo 'Radunate i Troiani, ite'
Idomeneo, re di Creta, K. 366: 4. Aria 'Non ho colpa'
Idomeneo, re di Creta, K. 366: 5. Recitativo 'Ecco il misero resto de’ Troiani'
Idomeneo, re di Creta, K. 366: 6. Coro 'Godiam la pace, trionfi Amore'
Idomeneo, re di Creta, K. 366: 7. Recitativo 'Prence, signor, tutta la Grecia oltraggi'
Idomeneo, re di Creta, K. 366: 8. Recitativo 'Estinto è Idomeneo?'
Idomeneo, re di Creta, K. 366: 9. Aria 'Tutte nel cor vi sento'
Idomeneo, re di Creta, K. 366: 10. Coro 'Pietà! Numi, pietà!'
Idomeneo, re di Creta, K. 366: 11. Pantomima e Recitativo 'Eccoci salvi alfin'
Idomeneo, re di Creta, K. 366: 12. Recitativo 'Tranquillo è il mar'
Idomeneo, re di Creta, K. 366: 13. Aria 'Vedrommi intorno l’ombra dolente'
Idomeneo, re di Creta, K. 366: 14. Recitativo 'Spiagge romite'
Idomeneo, re di Creta, K. 366: 15. Aria 'Il padre adorato'
Idomeneo, re di Creta, K. 366: 16. Intermezzo Marcia
Idomeneo, re di Creta, K. 366: 17. Coro 'Nettuno s’onori, quel nome risuoni'
Idomeneo, re di Creta, K. 366: 1. Recitativo 'Siam soli. Odimi, Arbace'
Idomeneo, re di Creta, K. 366: 2. Aria 'Se il tuo duol'
Idomeneo, re di Creta, K. 366: 3. Recitativo 'Se mai pomposo apparse'
Idomeneo, re di Creta, K. 366: 4. Aria 'Se il padre perdei'
Idomeneo, re di Creta, K. 366: 5. Recitativo 'Qual mi conturba i sensi'
Idomeneo, re di Creta, K. 366: 6. Aria 'Fuor del mar'
Idomeneo, re di Creta, K. 366: 7. Recitativo 'Chi mai del mio provò'
Idomeneo, re di Creta, K. 366: 8. Aria 'Idol mio, se ritroso'
Idomeneo, re di Creta, K. 366: 9. Marcia 'Odo da lunge armonioso suono'
Idomeneo, re di Creta, K. 366: 10. Recitativo 'Sidonie sponde!'
Idomeneo, re di Creta, K. 366: 11. Coro 'Placido è il mar, andiamo'
Idomeneo, re di Creta, K. 366: 12. Recitativo 'Vattene, prence'
Idomeneo, re di Creta, K. 366: 13. Terzetto 'Pria di partir, o Dio!'
Idomeneo, re di Creta, K. 366: 14. Coro 'Qual nuovo terrore!'
Idomeneo, re di Creta, K. 366: 15. Recitativo 'Eccoti in me, barbaro nume'
Idomeneo, re di Creta, K. 366: 16. Coro 'Corriamo, fuggiamo'
Idomeneo, re di Creta, K. 366: 1. Recitativo 'Solitudini amiche'
Idomeneo, re di Creta, K. 366: 2. Aria 'Zeffiretti lusinghieri'
Idomeneo, re di Creta, K. 366: 3. Recitativo 'Principessa, a’ tuoi sguardi'
Idomeneo, re di Creta, K. 366: 4. Duetto 'S’io non moro a questi accenti'
Idomeneo, re di Creta, K. 366: 5. Recitativo 'Cieli! che vedo?'
Idomeneo, re di Creta, K. 366: 6. Quartetto 'Andrò ramingo e solo'
Idomeneo, re di Creta, K. 366: 7. Recitativo 'Sventurata Sidon!'
Idomeneo, re di Creta, K. 366: 8. Aria 'Se colà ne’ fati è scritto'
Idomeneo, re di Creta, K. 366: 9. Recitativo 'Volgi intorno lo sguardo, o sire'
Idomeneo, re di Creta, K. 366: 10. Coro 'Oh, voto tremendo!'
Idomeneo, re di Creta, K. 366: 11. Marcia
Idomeneo, re di Creta, K. 366: 12. Cavatina con coro 'Accogli, o re del mar'
Idomeneo, re di Creta, K. 366: 13. Coro 'Stupenda vittoria!'– Recitativo 'Qual risuona qui intorno'
Idomeneo, re di Creta, K. 366: 14. Recitativo 'Padre, mio caro padre'
Idomeneo, re di Creta, K. 366: 15. Recitativo 'Ferma, o sire, che fai?'
Idomeneo, re di Creta, K. 366: 16. Aria 'Ha vinto Amore'
Idomeneo, re di Creta, K. 366: 17. Recitativo 'O ciel pietoso!'
Idomeneo, re di Creta, K. 366: 18. Aria 'D’Oreste, d’Aiace'
Idomeneo, re di Creta, K. 366: 19. Recitativo 'Popoli, a voi l’ultima legge'
Idomeneo, re di Creta, K. 366: 20. Aria 'Torna la pace'
Idomeneo, re di Creta, K. 366: 21. Coro 'Scenda Amor, scenda Imeneo'
